### PR TITLE
feat(model): add `userSchema` in `activityModel.js`

### PR DESCRIPTION
**Pull request by Aierbote**

### CODE REVIEW

**Review by RiccardoGrimaudo — APPROVED** [review]

**Review by alessandrocolla — CHANGES_REQUESTED** [review]
Required message isn't compliant to the schema.

**Review by alessandrocolla — APPROVED** [review]
Ok, everything alright

**Review by RiccardoGrimaudo — APPROVED** [review]

**Review by Accia97 — APPROVED** [review]
Bravo erto

**Review by PieroCarimi — APPROVED** [review]
Well done!

**Pull request merged**
