### PR TITLE
fix(api): fix of the filteredBody field

### PR DESCRIPTION
**Pull request by RiccardoGrimaudo**
fix of the filteredBody field

### CODE REVIEW

**Review by PieroCarimi — APPROVED** [review]
To review the filteredBody

**Review by Accia97 — CHANGES_REQUESTED** [review]
A user who's not an admin shouldn't be able to update "isActive", "isAccepted", "creationDate" and "hireDate" fields

**Review by Accia97 — APPROVED** [review]
👌

**Review by Aierbote — APPROVED** [review]
👌

**Pull request merged**
