### PR TITLE
feat(api): added task get route and controller

### PR DESCRIPTION
**Pull request by alessandrocolla**
Added Controllers and Routes folders, added task router, added task GET method.

### CODE REVIEW

**Review by PieroCarimi — APPROVED** [review]
Good job !

**Review by Accia97 — APPROVED** [review]
C'è tutto

**Review by RiccardoGrimaudo — APPROVED** [review]

**Review by Aierbote — COMMENTED** [review]
Should it be something like this?

```js 
res.status(200).json({
      status: "success",
      results: tasks.length,
      data: { tasks },
    });
  ```

**Review by Aierbote — APPROVED** [review]
👍

**Pull request merged**
